### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by Ash1ss** [9P9/Discord-QR-Token-Logger#1]
i have the correct chrom driver and i have installed the requirements and python 3.7.6 but when i run it it sais "Traceback (most recent call last):
  File "qr_generator.py", line 99, in <module>
    main()
  File "qr_generator.py", line 37, in main
    driver = webdriver.Chrome(options=options, executable_path=r'chromedriver.exe')
  File "C:\Python3\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Python3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Failed to create Chrome process.

Press any key to continue . . ."

**Comment by 6969penis** [comment]
please help

**Comment by alienw4re** [comment]
you got logged, hes using a vm so its a virus

**Comment by brrrrr7269** [comment]
did you install chrome driver?

**Comment by 6969penis** [comment]
alien its now a virus it normally works, and brrr yes im using the right chrome driver and ive tried like 4 other chrome drivers

**Comment by 6969penis** [comment]
> did you install chrome driver?

yes

**Comment by 6969penis** [comment]
> you got logged, hes using a vm so its a virus

its not a virus

**Comment by brrrrr7269** [comment]
did you put the chrome driver in the folder and check ur google version and try downloading chrome driver that says ur version

**Comment by bilalraj3232** [comment]
same issue

**Comment by the-cult-of-integral** [comment]
Try [this fork](https://github.com/the-cult-of-integral/Discord-QR-Token-Logger). This fork contains filed needed for compatible chrome browser and driver.

**Comment by ThatTSGuy** [comment]
This one removes the need for web scraping, and it's also much faster: https://github.com/ThatTSGuy/discord-qr-token-grabber
