### ISSUE TITLE
run bat keep closing not do anything

### ISSUE THREAD

**Issue by xuxu865** [9P9/Discord-QR-Token-Logger#16]
so i was able to build the image once but it didnt work so i try again with different chrome drive but nothing happen. i deleted folder and extract it again but now it wont build at all

**Comment by xuxu865** [comment]
working version https://github.com/the-cult-of-integral/Discord-QR-Token-Logger

be nice if this grab tokens without having to leave cmd prompt open

**Comment by mouadessalim** [comment]
@xuxu865 it's not necessary to hide the console because you need to understand that the generated qr code has a expiration date, so you need to generate the code for a specific victim and for a short time.
