### ISSUE TITLE
Can i be a colaborator ?

### ISSUE THREAD

**Issue by mouadessalim** [9P9/Discord-QR-Token-Logger#25]
Hey @9P9, as you see i am currently working hard to contribute. I've just want to ask you if you can add me like a colaborator to have write access. Actually i need to use pull requests to push code it can be better if i have direct write access. if you want to add me like a colaborator you follow these instruction:

![image](https://user-images.githubusercontent.com/38190847/187006693-87f568c2-9539-4f8d-b028-8227be499a6a.png)
 You need to put my github username which is: `mouadessalim` 

If you don't want to add me like a colaborator you can close this issue😔.

**Comment by 9P9** [comment]
Hi! I've gone ahead and added you as a collaborator since I haven't personally worked on this project for a while :) Please take good care of it! 

Appreciate all the work you've done on it so far
