### ISSUE TITLE
Please update some repository preference

### ISSUE THREAD

**Issue by mouadessalim** [9P9/Discord-QR-Token-Logger#26]
Hey @9P9  hope you're good i've worked all the day to get a brand new readme 😍. I've just want to tell if you can disable Wiki ans project section and also to hide release, environnement and packages section

![image](https://user-images.githubusercontent.com/38190847/187051853-6462a45f-31cd-4f44-8455-a26e88606477.png)

![image](https://user-images.githubusercontent.com/38190847/187051897-03120078-23ef-4bf1-862a-872954000e41.png)

**Comment by 9P9** [comment]
Hi there! I've made these changes on the project for you, if there is any chance you could put a link to my newer project of the website qr code method in the read-me that would be great :) 

Thanks!
