### ISSUE TITLE
I need help on how to install and run this

### ISSUE THREAD

**Issue by droperdu** [9P9/Discord-QR-Token-Logger#28]

**Comment by droperdu** [comment]
Nevermind I got it mb

**Comment by droperdu** [comment]
Where can I find the qr code?

**Comment by mouadessalim** [comment]
This issue doesn't follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CONTRIBUTING.md). Thank you for updating the issue, in case of no change the issue **_may be closed_**. Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CONTRIBUTING.md) and [code of conduct](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CODE_OF_CONDUCT.md).

**The issue doesn't respect this instruction:**

https://github.com/9P9/Discord-QR-Token-Logger/blob/4e3e49d6fcd26bb3b8e1b3a19fb60238afa91a7c/CONTRIBUTING.md?plain=1#L29

**Bideway, here is the answer for your question:**

https://github.com/9P9/Discord-QR-Token-Logger/blob/4e3e49d6fcd26bb3b8e1b3a19fb60238afa91a7c/README.md?plain=1#L49

@droperdu
