### ISSUE TITLE
Python module bug

### ISSUE THREAD

**Issue by PainDe0Mie** [9P9/Discord-QR-Token-Logger#36]
Here is my bug:

  File "C:\Users\Elexyr22\Downloads\Discord-QR-Token-Logger-main\main.py", line 26, in <module>
    from pystray import Icon, Menu, MenuItem
ModuleNotFoundError: No module named 'pystray'

I have the latest version of python and I uninstalled and reinstalled the modules but still nothing :/

**Comment by mouadessalim** [comment]
please try on a terminal : `pip3 install beautifulsoup4 lxml pillow requests selenium discord_webhook pystray pystyle webdriver_manager --upgrade`
