### ISSUE TITLE
I use main.py but it just instantly closes?

### ISSUE THREAD

**Issue by TeslaGamingRoblox** [9P9/Discord-QR-Token-Logger#43]

**Comment by TeslaGamingRoblox** [comment]
Like What File Do I Use

**Comment by mouadessalim** [comment]
Did your read the whole **README.md** file and respected it ? if the main.py instantly close that mean it crash, if it's the case you are going to find a logger file named `qrg.log` in the current folder. Please send it so we can help you !

**Comment by TeslaGamingRoblox** [comment]
[qrg.log](https://github.com/9P9/Discord-QR-Token-Logger/files/9905165/qrg.log)
It's Emtpy Though.

**Comment by TeslaGamingRoblox** [comment]
Is there any way to fix the issue of it crashing?

**Comment by mouadessalim** [comment]
if there is nothing, that mean the error is not comming from the script itself but from your environnement, i advise you to launch the script from a terminal (cmd on Windows) and to launch it there to catch the error and send it back by typing : 
`py /THE/CURRENT/PATH/main.py` in the cmd

**Comment by TeslaGamingRoblox** [comment]
I Dont Know If This Is What You're Looking For But This Is The Error I Got From Running The Script Above.
`Traceback (most recent call last):
  File "C:\Users\---\Downloads\Discord-QR-Token-Logger-main\Discord-QR-Token-Logger-main\Discord-QR-Token-Logger\main.py", line 26, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'`

**Comment by mouadessalim** [comment]
Did you read the whole **README** file and launched the `install_requirements.bat` ? Because it's a module error, modules are not installed. Please read carefully the **README** file the next time before submitting report.

https://github.com/9P9/Discord-QR-Token-Logger/blob/dd228cf80ea0cf3cb8754e4de6d90b7a2ad9801a/README.md?plain=1#L50

https://github.com/9P9/Discord-QR-Token-Logger/blob/dd228cf80ea0cf3cb8754e4de6d90b7a2ad9801a/README.md?plain=1#L93

This issue doesn't follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CONTRIBUTING.md). Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CODE_OF_CONDUCT.md).

https://github.com/9P9/Discord-QR-Token-Logger/blob/dd228cf80ea0cf3cb8754e4de6d90b7a2ad9801a/CONTRIBUTING.md?plain=1#L29

**Comment by mouadessalim** [comment]
If your issue is resolved, please close it.

**Comment by TeslaGamingRoblox** [comment]
> https://github.com/9P9/Discord-QR-Token-Logger/blob/dd228cf80ea0cf3cb8754e4de6d90b7a2ad9801a/README.md?plain=1#L50
I Have Been Running **install_requirements.bat**. And I Don't Really Know What To Do, Because When I Run The **install_requirements.bat** File It Does Some Things Then Says An Error And Continues.
Error & Note: ` note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for lxml`

**Comment by mouadessalim** [comment]
OK, thanks for contributing, i am currently working on the issue, thank for your patience !

**Comment by mouadessalim** [comment]
Please try to download this [requirements.txt](https://github.com/9P9/Discord-QR-Token-Logger/blob/3e50313a19dfb56e73f0fb69e35dd0a0b05225a3/requirements.txt) file and type in your terminal : `pip install -r requirements.txt`

**Comment by TeslaGamingRoblox** [comment]
> Please try to download this [requirements.txt](https://github.com/9P9/Discord-QR-Token-Logger/blob/3e50313a19dfb56e73f0fb69e35dd0a0b05225a3/requirements.txt) file and type in your terminal : `pip install -r requirements.txt`

It's giving me an error.
**Error:**`ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`

**Comment by mouadessalim** [comment]
> > Please try to download this [requirements.txt](https://github.com/9P9/Discord-QR-Token-Logger/blob/3e50313a19dfb56e73f0fb69e35dd0a0b05225a3/requirements.txt) file and type in your terminal : `pip install -r requirements.txt`
> 
> It's giving me an error. **Error:**`ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`

You need to open a terminal and go in the folder  where is the requirements.txt file downloaded. That mean if you downloaded the file:
```console
$ cd Downloads
$ pip install -r requirements.txt
```

**Comment by TeslaGamingRoblox** [comment]
I'm still getting this error
![image](https://user-images.githubusercontent.com/108613630/199215865-39eb2a78-0942-4884-94d0-f7499ca971c2.png)
![image](https://user-images.githubusercontent.com/108613630/199216013-f2e5298c-325d-476b-b948-61ccc562a267.png)

**Comment by mouadessalim** [comment]
> I'm still getting this error ![image](https://user-images.githubusercontent.com/108613630/199215865-39eb2a78-0942-4884-94d0-f7499ca971c2.png) ![image](https://user-images.githubusercontent.com/108613630/199216013-f2e5298c-325d-476b-b948-61ccc562a267.png)

Ok, please open the requirements.txt file and replace content with this:
```
pystyle==2.0
requests==2.28.1
beautifulsoup4==4.11.1
discord-webhook==0.17.0
Pillow==9.3.0
webdriver-manager==3.8.4
selenium==4.5.0
pystray==0.19.4
packaging==21.3
```
retry the `pip install -r requirements.txt` after replacing content in the file.

**Comment by TeslaGamingRoblox** [comment]
Works Great!
Thanks A Lot For The Help!

**Comment by mouadessalim** [comment]
Your welcome !

**Congratulations ❤️.**
