### ISSUE TITLE
libxml2

### ISSUE THREAD

**Issue by ccster1** [9P9/Discord-QR-Token-Logger#44]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [y] I am running the latest version
- [y ] I checked the documentation and found no answer
- [y ] I checked to make sure that this issue has not already been filed
- [ y] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting 
i was expecting for lxml to install correctly

# Current Behavior

What is the current behavior?
lxml fails to install

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Firmware Version:
* Operating System:
* SDK version:
* Toolchain version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by ccster1** [comment]
![Screenshot 2022-10-31 170136](https://user-images.githubusercontent.com/117122245/199110575-92a5c059-bf49-4068-86de-4b21e7ac8b08.png)
[Discord-QR-Token-Logger-main (2).zip](https://github.com/9P9/Discord-QR-Token-Logger/files/9905041/Discord-QR-Token-Logger-main.2.zip)

**Comment by mouadessalim** [comment]
you're error is kinda weird, it's not a pythonic error but a c programming language error, are you sure that you've applicated the whole instructions in the README file and that you've launched the `main.py` with your python interpreter ?

**Comment by mouadessalim** [comment]
Please read this comment: https://github.com/9P9/Discord-QR-Token-Logger/issues/43#issuecomment-1298326588
