### ISSUE TITLE
Stuck On Generating QR Code

### ISSUE THREAD

**Issue by TeslaGamingRoblox** [9P9/Discord-QR-Token-Logger#46]
Bug Report
**main.py** Stuck On Generating QR Code.
'Stuck On Generating QR Code'
bug,webhook

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

I Was Expecting The QR Code To Generate.

It Is Currently Just Stuck Generating The QR Code.
**Saying**: `Generating QR Code`

I Am Also Getting A qrg.log File.
**Saying**:`[logger.py:26 -              wrapper() ] Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
`

**Comment by TeslaGamingRoblox** [comment]
Am I doing something wrong?

**Comment by mouadessalim** [comment]
Hey,  i've changed some things in the script, please replace your `main.py` with this [one](https://github.com/9P9/Discord-QR-Token-Logger/blob/83e4eb31fb975d3200f6cd00d539fd2c9edb7326/Discord-QR-Token-Logger/main.py)
