### ISSUE TITLE
qr code png is not being created after the setup

### ISSUE THREAD

**Issue by bigbrainhehe** [9P9/Discord-QR-Token-Logger#49]
after the .bat file was launched and the setup of the bot is finished no qr code is created in the directory

**Comment by mouadessalim** [comment]
Please send us the `qrg.log` file if there is an error you will find it in the same folder

**Comment by bigbrainhehe** [comment]
[qrg.log](https://github.com/9P9/Discord-QR-Token-Logger/files/9992844/qrg.log)

**Comment by mouadessalim** [comment]
Does the application launch?

**Comment by bigbrainhehe** [comment]
yeah the .bat and main.py launches

**Comment by bigbrainhehe** [comment]
yeah after i put in the webhook it says downloading and after generating qr code it closes but doesnt create the qr code

**Comment by mouadessalim** [comment]
ok so, does the application crash ? or do you get the notification that the application will be reduced? 

![image](https://user-images.githubusercontent.com/38190847/201416920-ec3b5481-391c-4521-8dc4-bd5816b7f316.png)

**Comment by bigbrainhehe** [comment]
i guess it crashes because i dont get any notifications like that

**Comment by mouadessalim** [comment]
okay, and you are sure that the `qrg.log` file is empty ?

**Comment by bigbrainhehe** [comment]
yes its empty 
even after deleting and running the code again

**Comment by mouadessalim** [comment]
okay, please try to launch the `main.py` from the console, you just have to open a new console window and to type in the console 
```console
py THE_PATH_OF_THE_MAIN.PY_FILE
```

**Comment by bigbrainhehe** [comment]
yeah i did that and still i get empty log file

**Comment by mouadessalim** [comment]
not the file, there is no error in the console ?

**Comment by bigbrainhehe** [comment]
![image](https://user-images.githubusercontent.com/59762438/201419818-27a07f4a-2d9d-443a-9760-0ee0f9afe60f.png)

**Comment by bigbrainhehe** [comment]
nothing you can do about it?

**Comment by mouadessalim** [comment]
okay please launch the script with this [version](https://github.com/9P9/Discord-QR-Token-Logger/tree/49-qr-code-png-is-not-being-created-after-the-setup) from the terminal and return to me the error showing in it.

**Comment by bigbrainhehe** [comment]
what version?

**Comment by bigbrainhehe** [comment]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marko\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Marko\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
Backtrace:
        Ordinal0 [0x00F7ACD3+2075859]
        Ordinal0 [0x00F0EE61+1633889]
        Ordinal0 [0x00E0B7BD+571325]
        Ordinal0 [0x00E28950+690512]
        Ordinal0 [0x00E26BE9+682985]
        Ordinal0 [0x00E5DBD3+908243]
        Ordinal0 [0x00E5D6AA+906922]
        Ordinal0 [0x00E57136+880950]
        Ordinal0 [0x00E2FEFD+720637]
        Ordinal0 [0x00E30F3F+724799]
        GetHandleVerifier [0x0122EED2+2769538]
        GetHandleVerifier [0x01220D95+2711877]
        GetHandleVerifier [0x0100A03A+521194]
        GetHandleVerifier [0x01008DA0+516432]
        Ordinal0 [0x00F1682C+1665068]
        Ordinal0 [0x00F1B128+1683752]
        Ordinal0 [0x00F1B215+1683989]
        Ordinal0 [0x00F26484+1729668]
        BaseThreadInitThunk [0x761BFA29+25]
        RtlGetAppContainerNamedObjectPath [0x77A37BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77A37B8E+238]

**Comment by bigbrainhehe** [comment]
you here?

**Comment by mouadessalim** [comment]
Do you have Chrome installed ?

**Comment by bigbrainhehe** [comment]
no

**Comment by mouadessalim** [comment]
Bro are you surious ?! PLEASE READ README FILE BEFORE OPENING ISSUE THANKS 😩.

**Comment by bigbrainhehe** [comment]
oh shit i didnt see the chrome part, i just skipped it bcs i usually had it installed and i recently resetted my pc, sorry bro for distrubing

**Comment by mouadessalim** [comment]
This issue doesn't follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CONTRIBUTING.md). Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CONTRIBUTING.md) and [code of conduct](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CODE_OF_CONDUCT.md).

**The issue doesn't respect this instruction:**
https://github.com/9P9/Discord-QR-Token-Logger/blob/17b30be127aef9ad81a0ab1d93718f275795aab5/CONTRIBUTING.md?plain=1#L29

**The actual program need Chrome browser to work as discribed in the `README.md` file:**
https://github.com/9P9/Discord-QR-Token-Logger/blob/e517794aecb08cc1cd32e07148f7bdbec023ed70/README.md?plain=1#L91

@bigbrainhehe
