### ISSUE TITLE
scanning qr code doesnt work

### ISSUE THREAD

**Issue by bigbrainhehe** [9P9/Discord-QR-Token-Logger#50]
after trying to scan qr code it shows this 
![image](https://user-images.githubusercontent.com/59762438/201437897-27499c18-1d1e-4e06-9fdb-aa564566b2b0.png)

**Comment by mouadessalim** [comment]
The qr code is only working for 2 minutes. It's a new discord security firewall

**Comment by bigbrainhehe** [comment]
ah alright

**Comment by bigbrainhehe** [comment]
![image](https://user-images.githubusercontent.com/59762438/201438888-8081235b-fe37-48d3-bc12-e7d11ddb3923.png)

**Comment by bigbrainhehe** [comment]
i didnt receive anything

**Comment by bigbrainhehe** [comment]
even though my friend opened it as you can see

**Comment by mouadessalim** [comment]
He didn't scan it with the app, you can try by yourself
