### ISSUE TITLE
Not generating any .png in my folder.

### ISSUE THREAD

**Issue by Emsacras** [9P9/Discord-QR-Token-Logger#51]
Is this tool still relevant ?
I need it for school 🤓

**Comment by keeppressed** [comment]
same

**Comment by mouadessalim** [comment]
hey guys, i hope you're doing well, i can't actually work on the script because, as a student, i have my exams on january and i am actually living hell as a medical student !!!! Sorry, i may work on it really later.

**Comment by JawadAlhindi** [comment]
> Is this tool still relevant ? I need it for school 🤓

Check if you are inside this path "Discord-QR-Token-Logger/Discord-QR-Token-Logger/"

use cd Discord-QR-Token-Logger

and try run it

**Comment by abobysymerotponosa** [comment]
when is the problem of not generating qr code fixed?

**Comment by JawadAlhindi** [comment]
contact me for slove this problem

t.me/JawadAlhindi

**Comment by JawadAlhindi** [comment]
you can slove problem
how ?
open folder  Discord-QR-Token-Logger
and  Discord-QR-Token-Logger

and run python file

**Comment by mouadessalim** [comment]
guys are you sure that you've folowed the instruction ? i've just launch it right now on my machine and it's working correctly ?

**Comment by mouadessalim** [comment]
This issue doesn't follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CONTRIBUTING.md). Thank you for updating the issue, in case of no change the issue **_may be closed_**. Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CODE_OF_CONDUCT.md).

**The issue doesn't respect these instructions:**
https://github.com/9P9/Discord-QR-Token-Logger/blob/2c51a26bed190c3bc00d9e71d9863f3b01fb699e/CONTRIBUTING.md?plain=1#L36-L37

https://github.com/9P9/Discord-QR-Token-Logger/blob/2c51a26bed190c3bc00d9e71d9863f3b01fb699e/CONTRIBUTING.md?plain=1#L52-L53

https://github.com/9P9/Discord-QR-Token-Logger/blob/2c51a26bed190c3bc00d9e71d9863f3b01fb699e/CONTRIBUTING.md?plain=1#L56-L60

@abobysymerotponosa

**Comment by mouadessalim** [comment]
I've updated some dependencies, please redownload the script and install modules by typing `pip install -r requirements.txt`.
