### ISSUE TITLE
Wont run

### ISSUE THREAD

**Issue by Gl1tch0436** [9P9/Discord-QR-Token-Logger#55]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

**Expected Behavior**
I'm expecting it to run

**Current Behavior**
for some reason it wont run and closes the moment it gets opened

**Failure Information (for bugs)**
it wont run

**Comment by Bonkand** [comment]
did you install the requirements?

**Comment by oji6ixx** [comment]
> 

hey im having the same problem the requirements wont install
