### ISSUE TITLE
Discord Fake Verification Bot

### ISSUE THREAD

**Issue by daffysnuts** [9P9/Discord-QR-Token-Logger#60]
![image](https://user-images.githubusercontent.com/109834830/220084715-7cf00bd3-d3fe-438e-8bea-63e9ccd28e49.png)

If possible can you make a bot like this, thanks

**Comment by mouadessalim** [comment]
These bots can't work anymore after discord adding a fire wall security check of ip location

**Comment by tidex0** [comment]
they do work
