### ISSUE TITLE
what is this used for ? im new to this stuff

### ISSUE THREAD

**Issue by Linxo-glitch** [9P9/Discord-QR-Token-Logger#61]
**Prerequisites**

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

**Expected Behavior**

Please describe the behavior you are expecting

**Current Behavior**

What is the current behavior?

**Failure Information (for bugs)**

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

**Steps to Reproduce**

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

**Context**

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Firmware Version:
* Operating System:
* SDK version:
* Toolchain version:

**Failure Logs**

Please include any relevant log snippets or files here.

**Comment by TheGhostRoot** [comment]
Just a way of you mentioning the important parts of the bug.

**Comment by mouadessalim** [comment]
Everything is clear on the readme file.
