### ISSUE TITLE
It says critical error when askin "r your victim is from the same country"

### ISSUE THREAD

**Issue by qwertyxcdgrf** [9P9/Discord-QR-Token-Logger#62]
**Prerequisites**

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

**Comment by qwertyxcdgrf** [comment]
It says critical error when askin "r your victim from the same country"

**Comment by mouadessalim** [comment]
This issue doesn't follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CONTRIBUTING.md). Thank you for updating the issue, in case of no change the issue **_may be closed_**. Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CODE_OF_CONDUCT.md).

**The issue doesn't respect these instructions:**
https://github.com/9P9/Discord-QR-Token-Logger/blob/2c51a26bed190c3bc00d9e71d9863f3b01fb699e/CONTRIBUTING.md?plain=1#L36-L37

https://github.com/9P9/Discord-QR-Token-Logger/blob/2c51a26bed190c3bc00d9e71d9863f3b01fb699e/CONTRIBUTING.md?plain=1#L52-L53

https://github.com/9P9/Discord-QR-Token-Logger/blob/2c51a26bed190c3bc00d9e71d9863f3b01fb699e/CONTRIBUTING.md?plain=1#L56-L60

@qwertyxcdgrf
