### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by Romahorkov** [9P9/Discord-QR-Token-Logger#66]
At least I did everything right

**Comment by mouadessalim** [comment]
This issue doesn't follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CONTRIBUTING.md). Thank you for updating the issue, in case of no change the issue **_may be closed_**. Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CODE_OF_CONDUCT.md).

**The issue doesn't respect these instructions:**
https://github.com/9P9/Discord-QR-Token-Logger/blob/2c51a26bed190c3bc00d9e71d9863f3b01fb699e/CONTRIBUTING.md?plain=1#L36-L37

https://github.com/9P9/Discord-QR-Token-Logger/blob/2c51a26bed190c3bc00d9e71d9863f3b01fb699e/CONTRIBUTING.md?plain=1#L52-L53

https://github.com/9P9/Discord-QR-Token-Logger/blob/2c51a26bed190c3bc00d9e71d9863f3b01fb699e/CONTRIBUTING.md?plain=1#L56-L60

@Romahorkov

**Comment by Romahorkov** [comment]
python  3.10.11
nodejs 16.14.0
npm 8.3.1

**Comment by Romahorkov** [comment]
after installing the recommended actions, it crashes immediately at startup

**Comment by mouadessalim** [comment]
This issue doesn't follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CONTRIBUTING.md). Thank you for updating the issue, in case of no change the issue **_may be closed_**. Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/9P9/Discord-QR-Token-Logger/blob/main/CODE_OF_CONDUCT.md).

**The issue doesn't respect these instructions:**
https://github.com/9P9/Discord-QR-Token-Logger/blob/2c51a26bed190c3bc00d9e71d9863f3b01fb699e/CONTRIBUTING.md?plain=1#L56-L60

@Romahorkov

**Comment by Romahorkov** [comment]
error `C:\Users\romah\OneDrive\Рабочий стол\Discord-QR-Token-Logger-main\Discord-QR-Token-Logger>main.py
Traceback (most recent call last):
  File "C:\Users\romah\OneDrive\Рабочий стол\Discord-QR-Token-Logger-main\Discord-QR-Token-Logger\main.py", line 24, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'`

**Comment by mouadessalim** [comment]
did you installed the requirements ?

**Comment by Romahorkov** [comment]
didn't understand what these requirements are?
Chrome: be sure to have the latest version.
Python 3.9+
Python Modules (launch pip install -r requirements.txt)
GTK 3 Runtime

**Comment by Romahorkov** [comment]
i install requirements
