### ISSUE TITLE
CAIRO SVG BUG ON APP

### ISSUE THREAD

**Issue by PetriJokinen** [9P9/Discord-QR-Token-Logger#68]
Shows this when i run the app even tho i have cairosvg downloaded

OSError: no library called "cairo-2" was found
no library called "cairo" was found
cannot load library 'C:\GTK\bin\libcairo-2.dll': error 0xc1
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

**Comment by mouadessalim** [comment]
can you give us more information on what's the step that you've done to get the bug.

**Comment by PetriJokinen** [comment]
I have basically installed all the required packages. and then when i try to run the program it shows this error

**Comment by mouadessalim** [comment]
Did you installed the GTK runtime ?

**Comment by PetriJokinen** [comment]
yes i have

**Comment by daffysnuts** [comment]
i finally fixed it if you want it
