### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by PaZapdc** [9P9/Discord-QR-Token-Logger#69]
ı try visual code but not working
![image](https://github.com/9P9/Discord-QR-Token-Logger/assets/121311588/0808e879-0c99-42f0-a72c-846bcb2c435d)
![image](https://github.com/9P9/Discord-QR-Token-Logger/assets/121311588/37e65db3-ad21-40db-bfee-9d05881c9af7)

**Comment by mouadessalim** [comment]
This repository has been archived and is no longer maintained. Please note that no further updates or support will be provided.
