### ISSUE TITLE
Program Not Working

### ISSUE THREAD

**Issue by VSPuzzler** [9P9/Discord-QR-Token-Logger#7]
I get this error:
```

[!] QR Code Token Logger Generator 

C:\Users\Vineet Saravanan\Downloads\Discord-QR-Token-Logger-main\Discord-QR-Token-Logger-main\QR_Generator.py:37: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(options=options, executable_path=r'chromedriver.exe')
Traceback (most recent call last):
  File "C:\Users\Vineet Saravanan\Downloads\Discord-QR-Token-Logger-main\Discord-QR-Token-Logger-main\QR_Generator.py", line 99, in <module>
    main()
  File "C:\Users\Vineet Saravanan\Downloads\Discord-QR-Token-Logger-main\Discord-QR-Token-Logger-main\QR_Generator.py", line 37, in main
    driver = webdriver.Chrome(options=options, executable_path=r'chromedriver.exe')
  File "C:\Users\Vineet Saravanan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Vineet Saravanan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Vineet Saravanan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Vineet Saravanan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Vineet Saravanan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Vineet Saravanan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 89
Current browser version is 97.0.4692.99 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
	Ordinal0 [0x008FE7D3+124883]
	Ordinal0 [0x008FE7B1+124849]
	GetHandleVerifier [0x00B48688+193832]
	GetHandleVerifier [0x00B63AC5+305509]
	GetHandleVerifier [0x00B6021B+291003]
	GetHandleVerifier [0x00B5E0AC+282444]
	GetHandleVerifier [0x00B84A90+440624]
	GetHandleVerifier [0x00B847FC+439964]
	GetHandleVerifier [0x00B8154B+426987]
	GetHandleVerifier [0x00B64FFD+310941]
	GetHandleVerifier [0x00B65D8E+314414]
	GetHandleVerifier [0x00B65D19+314297]
	GetHandleVerifier [0x00C231EC+1089676]
	GetHandleVerifier [0x00C217C9+1082985]
	GetHandleVerifier [0x00C213A3+1081923]
	GetHandleVerifier [0x00D1D9FD+2115741]
	Ordinal0 [0x00A4B82E+1488942]
	Ordinal0 [0x009E5A7D+1071741]
	Ordinal0 [0x009E559B+1070491]
	Ordinal0 [0x009E54B1+1070257]
	Ordinal0 [0x00A1FF53+1310547]
	BaseThreadInitThunk [0x771C6739+25]
	RtlGetFullPathName_UEx [0x77B18AFF+1215]
	RtlGetFullPathName_UEx [0x77B18ACD+1165]


Process finished with exit code 1
```
I already tried changing line 49 like other comments suggested.

**Comment by DOKKAEBIx** [comment]
I think discord patched this unless you can get a new version of the qr code it wont work

**Comment by PepeTheRoya** [comment]
> I get this error:
> 
> ```
> 
> [!] QR Code Token Logger Generator 
> 
> C:\Users\Vineet Saravanan\Downloads\Discord-QR-Token-Logger-main\Discord-QR-Token-Logger-main\QR_Generator.py:37: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
>   driver = webdriver.Chrome(options=options, executable_path=r'chromedriver.exe')
> Traceback (most recent call last):
>   File "C:\Users\Vineet Saravanan\Downloads\Discord-QR-Token-Logger-main\Discord-QR-Token-Logger-main\QR_Generator.py", line 99, in <module>
>     main()
>   File "C:\Users\Vineet Saravanan\Downloads\Discord-QR-Token-Logger-main\Discord-QR-Token-Logger-main\QR_Generator.py", line 37, in main
>     driver = webdriver.Chrome(options=options, executable_path=r'chromedriver.exe')
>   File "C:\Users\Vineet Saravanan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
>     super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
>   File "C:\Users\Vineet Saravanan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
>     RemoteWebDriver.__init__(
>   File "C:\Users\Vineet Saravanan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 268, in __init__
>     self.start_session(capabilities, browser_profile)
>   File "C:\Users\Vineet Saravanan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in start_session
>     response = self.execute(Command.NEW_SESSION, parameters)
>   File "C:\Users\Vineet Saravanan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
>     self.error_handler.check_response(response)
>   File "C:\Users\Vineet Saravanan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 89
> Current browser version is 97.0.4692.99 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
> Stacktrace:
> Backtrace:
> 	Ordinal0 [0x008FE7D3+124883]
> 	Ordinal0 [0x008FE7B1+124849]
> 	GetHandleVerifier [0x00B48688+193832]
> 	GetHandleVerifier [0x00B63AC5+305509]
> 	GetHandleVerifier [0x00B6021B+291003]
> 	GetHandleVerifier [0x00B5E0AC+282444]
> 	GetHandleVerifier [0x00B84A90+440624]
> 	GetHandleVerifier [0x00B847FC+439964]
> 	GetHandleVerifier [0x00B8154B+426987]
> 	GetHandleVerifier [0x00B64FFD+310941]
> 	GetHandleVerifier [0x00B65D8E+314414]
> 	GetHandleVerifier [0x00B65D19+314297]
> 	GetHandleVerifier [0x00C231EC+1089676]
> 	GetHandleVerifier [0x00C217C9+1082985]
> 	GetHandleVerifier [0x00C213A3+1081923]
> 	GetHandleVerifier [0x00D1D9FD+2115741]
> 	Ordinal0 [0x00A4B82E+1488942]
> 	Ordinal0 [0x009E5A7D+1071741]
> 	Ordinal0 [0x009E559B+1070491]
> 	Ordinal0 [0x009E54B1+1070257]
> 	Ordinal0 [0x00A1FF53+1310547]
> 	BaseThreadInitThunk [0x771C6739+25]
> 	RtlGetFullPathName_UEx [0x77B18AFF+1215]
> 	RtlGetFullPathName_UEx [0x77B18ACD+1165]
> 
> 
> Process finished with exit code 1
> ```
> 
> I already tried changing line 49 like other comments suggested.

You need new chromedriver. The one in the directory is old and is version 89 while you need version 98 or something like that since chromedriver is on that version today I think but just search up chromedriver and download the latest one and put the chromedriver.exe in the directory

**Comment by lordfrijoles** [comment]
> > I get this error:
> > ```
> > 
> > [!] QR Code Token Logger Generator 
> > 
> > C:\Users\Vineet Saravanan\Downloads\Discord-QR-Token-Logger-main\Discord-QR-Token-Logger-main\QR_Generator.py:37: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
> >   driver = webdriver.Chrome(options=options, executable_path=r'chromedriver.exe')
> > Traceback (most recent call last):
> >   File "C:\Users\Vineet Saravanan\Downloads\Discord-QR-Token-Logger-main\Discord-QR-Token-Logger-main\QR_Generator.py", line 99, in <module>
> >     main()
> >   File "C:\Users\Vineet Saravanan\Downloads\Discord-QR-Token-Logger-main\Discord-QR-Token-Logger-main\QR_Generator.py", line 37, in main
> >     driver = webdriver.Chrome(options=options, executable_path=r'chromedriver.exe')
> >   File "C:\Users\Vineet Saravanan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
> >     super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
> >   File "C:\Users\Vineet Saravanan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
> >     RemoteWebDriver.__init__(
> >   File "C:\Users\Vineet Saravanan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 268, in __init__
> >     self.start_session(capabilities, browser_profile)
> >   File "C:\Users\Vineet Saravanan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 359, in start_session
> >     response = self.execute(Command.NEW_SESSION, parameters)
> >   File "C:\Users\Vineet Saravanan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
> >     self.error_handler.check_response(response)
> >   File "C:\Users\Vineet Saravanan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
> >     raise exception_class(message, screen, stacktrace)
> > selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 89
> > Current browser version is 97.0.4692.99 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
> > Stacktrace:
> > Backtrace:
> > 	Ordinal0 [0x008FE7D3+124883]
> > 	Ordinal0 [0x008FE7B1+124849]
> > 	GetHandleVerifier [0x00B48688+193832]
> > 	GetHandleVerifier [0x00B63AC5+305509]
> > 	GetHandleVerifier [0x00B6021B+291003]
> > 	GetHandleVerifier [0x00B5E0AC+282444]
> > 	GetHandleVerifier [0x00B84A90+440624]
> > 	GetHandleVerifier [0x00B847FC+439964]
> > 	GetHandleVerifier [0x00B8154B+426987]
> > 	GetHandleVerifier [0x00B64FFD+310941]
> > 	GetHandleVerifier [0x00B65D8E+314414]
> > 	GetHandleVerifier [0x00B65D19+314297]
> > 	GetHandleVerifier [0x00C231EC+1089676]
> > 	GetHandleVerifier [0x00C217C9+1082985]
> > 	GetHandleVerifier [0x00C213A3+1081923]
> > 	GetHandleVerifier [0x00D1D9FD+2115741]
> > 	Ordinal0 [0x00A4B82E+1488942]
> > 	Ordinal0 [0x009E5A7D+1071741]
> > 	Ordinal0 [0x009E559B+1070491]
> > 	Ordinal0 [0x009E54B1+1070257]
> > 	Ordinal0 [0x00A1FF53+1310547]
> > 	BaseThreadInitThunk [0x771C6739+25]
> > 	RtlGetFullPathName_UEx [0x77B18AFF+1215]
> > 	RtlGetFullPathName_UEx [0x77B18ACD+1165]
> > 
> > 
> > Process finished with exit code 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I already tried changing line 49 like other comments suggested.
> 
> You need new chromedriver. The one in the directory is old and is version 89 while you need version 98 or something like that since chromedriver is on that version today I think but just search up chromedriver and download the latest one and put the chromedriver.exe in the directory

First of all does this still work and second of all i did it nothing changed.

**Comment by the-cult-of-integral** [comment]
Try [this fork](https://github.com/the-cult-of-integral/Discord-QR-Token-Logger). Compatible chrome driver and binary included within the fork.

**Comment by the-cult-of-integral** [comment]
Also @DOKKAEBIx is incorrect; this has not been patched as of 22nd April 2022.

**Comment by ThatTSGuy** [comment]
Try this one, it is impossible to patch out: https://github.com/ThatTSGuy/discord-qr-token-grabber

**Comment by mouadessalim** [comment]
This issue doesn't follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CONTRIBUTING.md). Thank you for updating the issue, in case of no change the issue will be closed in _**48 hours**_. Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CONTRIBUTING.md) and [code of conduct](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CODE_OF_CONDUCT.md).

**The issue doesn't respect these instructions:**

https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CONTRIBUTING.md?plain=1#L52

@VSPuzzler  @9P9

**Comment by mouadessalim** [comment]
Thank you @ThatTSGuy for deleting this [comment](https://github.com/9P9/Discord-QR-Token-Logger/issues/7#issuecomment-1186523907) because it doens't respect [code of conduct](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CODE_OF_CONDUCT.md). Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CONTRIBUTING.md) and [code of conduct](https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CODE_OF_CONDUCT.md).

**The  [comment](https://github.com/9P9/Discord-QR-Token-Logger/issues/7#issuecomment-1186523907) doesn't respect this instruction:**

https://github.com/9P9/Discord-QR-Token-Logger/blob/4de8eb749eeaa42bdbb48747b0fc1e440d1a19b2/CODE_OF_CONDUCT.md?plain=1#L22-L23
