### ISSUE TITLE
Everytime i use a https proxy and go to create the qr i get this error.

### ISSUE THREAD

**Issue by wayram** [9P9/Discord-QR-Token-Logger#75]
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: headless chrome=114.0.5735.199)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00C2A813+48355]
        (No symbol) [0x00BBC4B1]
        (No symbol) [0x00AC5358]
        (No symbol) [0x00AC1B33]
        (No symbol) [0x00AB8CA5]
        (No symbol) [0x00AB9D0A]
        (No symbol) [0x00AB9003]
        (No symbol) [0x00AB8355]
        (No symbol) [0x00AB82EC]
        (No symbol) [0x00AB6F26]
        (No symbol) [0x00AB7688]
        (No symbol) [0x00AC6B52]
        (No symbol) [0x00B1CF01]
        (No symbol) [0x00B0A73C]
        (No symbol) [0x00B1C922]
        (No symbol) [0x00B0A536]
        (No symbol) [0x00AE82DC]
        (No symbol) [0x00AE93DD]
        GetHandleVerifier [0x00E8AABD+2539405]
        GetHandleVerifier [0x00ECA78F+2800735]
        GetHandleVerifier [0x00EC456C+2775612]
        GetHandleVerifier [0x00CB51E0+616112]
        (No symbol) [0x00BC5F8C]
        (No symbol) [0x00BC2328]
        (No symbol) [0x00BC240B]
        (No symbol) [0x00BB4FF7]
        BaseThreadInitThunk [0x76D100C9+25]
        RtlGetAppContainerNamedObjectPath [0x771A7B1E+286]
        RtlGetAppContainerNamedObjectPath [0x771A7AEE+238]

**Comment by mouadessalim** [comment]
This repository has been archived and is no longer maintained. Please note that no further updates or support will be provided.
