### ISSUE TITLE
chrome driver doesnt exist

### ISSUE THREAD

**Issue by ProArcher24** [9P9/Discord-QR-Token-Logger#77]
**Steps to Reproduce**

Please provide detailed steps for reproducing the issue.

1. download all requirements
2. run main.py
3. get the error

**Context**

**Failure Logs**

![image](https://github.com/9P9/Discord-QR-Token-Logger/assets/69578164/00f5a019-c744-434f-8b1c-c598be7a8f97)

**Comment by ProArcher24** [comment]
full screenshot of error
![image](https://github.com/9P9/Discord-QR-Token-Logger/assets/69578164/4c361bb1-fa86-4928-8f5c-d72b8b000f16)

**Comment by ProArcher24** [comment]
get a new error after updating to newest version of python
![image](https://github.com/9P9/Discord-QR-Token-Logger/assets/69578164/8aa6e456-52e4-47af-ae20-badecf3a6a4d)

**Comment by mouadessalim** [comment]
This repository has been archived and is no longer maintained. Please note that no further updates or support will be provided.
