### ISSUE TITLE
Program is not working.

### ISSUE THREAD

**Issue by Lancmo** [9P9/Discord-QR-Token-Logger#82]
When I run the program by using the "py main.py" to start up the program it gives me the error shown in the screenshot below.

![image](https://github.com/9P9/Discord-QR-Token-Logger/assets/43474283/2badfa4b-d84c-4ca6-a77c-65a0c9e1042d)

**Comment by mouadessalim** [comment]
This repository has been archived and is no longer maintained. Please note that no further updates or support will be provided.
